### ISSUE TITLE
Version 2 error

### ISSUE THREAD

**Issue by oknoorap** [sindresorhus/log-symbols#10]
I got error with version 2

```bash
fs.js:651
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/oknoorap/workspace/git/playground/node_modules/log-symbols/node_modules/chalk/index.js'
    at Object.fs.openSync (fs.js:651:18)
    at Object.fs.readFileSync (fs.js:553:33)
    at Object.Module._extensions..js (module.js:579:20)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/oknoorap/workspace/git/playground/node_modules/log-symbols/index.js:3:15)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
```

**Comment by kevva** [comment]
Looks like `chalk` isn't properly installed. What `npm` version are you running?

**Comment by sindresorhus** [comment]
Try upgrading your npm version. If it's still a problem, try opening an issue here instead: https://github.com/npm/npm
